// Generated by CoffeeScript 2.7.0
(function() {
  var activate, deactivate, odog, vscode;

  vscode = require('vscode');

  // 调试通道
  odog = null;

  activate = function(context) {
    var disposable, otC;
    // 创建输出通道
    otC = vscode.window.createOutputChannel('贱狗');
    context.subscriptions.push(otC);
    odog = function(msg) {
      var time;
      time = new Date().toLocaleTimeString();
      otC.appendLine(`[${time}] ${msg}`);
      return console.log(`[贱狗${time}]: ${msg}`);
    };
    odog('KeyDog 插件已激活');
    disposable = vscode.commands.registerCommand('cofee.helloWorld', function() {
      return vscode.window.showInformationMessage('H道动!');
    });
    return context.subscriptions.push(disposable);
  };

  deactivate = function() {};

  module.exports = {activate, deactivate};

}).call(this);
